// actionTypes.js
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUESTE= 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT_USER = 'LOGOUT_USER';

export const SET_LOGGED_IN = 'SET_LOGGED_IN';

export const SEARCH_FRIEND = 'SEARCH_FRIEND'

export const GET_CHAT_ROOMS = 'GET_CHAT_ROOMS'
export const GET_REQUESTS = 'GET_REQUESTS'
export const GET_FRIENDS = 'GET_FRIENDS'
export const GET_SENDS = 'GET_SENDS'

export const JOIN_ROOM = 'JOIN_ROOM'
export const USER_ROOM = 'USER_ROOM'
export const GROUP_ROOM = 'GROUP_ROOM'
export const SINGLE_ROOM = 'SINGLE_ROOM'
export const GET_MESSAGES = 'GET_MESSAGES'
export const CREATE_CHAT_ROOM = 'CREATE_CHAT_ROOM'

export const UPDATE_PROFILE = 'UPDATE_PROFILE'